name: mobile_device_identifier_example
description: Demonstrates how to use the mobile_device_identifier plugin.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_device_identifier:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
